---
sudo: required

language: python

python:
  - '2.7'

services:
  - docker

before_install:
  - rvm default
  - gem install inspec

install:
  - virtualenv --python=$(which python2.7) .venv
  - source .venv/bin/activate
  - pip install -r requirements.txt

script:
  - ./test/test.sh
