---
# tasks file for ansible-role-pritunl-client

# we only support Ubuntu distribution
- assert:
    that:
      - "ansible_distribution == 'Ubuntu'"
    msg: "This role only supports Ubuntu distribution. {{ ansible_distribution }} is not yet supported!"

- name: Ensure all variable files based on the distribution are loaded.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"

- name: Ensure all tasks based on the distribution are loaded.
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"

- name: Ensure pritunl client service is started and enabled
  service:
    name: pritunl-client
    enabled: yes
    state: started
