---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: molecule/default/.yamllint.yml

platforms:
  - name: xenial
    image: ubuntu:16.04
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"

  - name: trusty
    image: ubuntu-upstart:14.04
    command: "/sbin/init"

  - name: precise
    image: ubuntu-upstart:12.04
    command: "/sbin/init"

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
